"""Phase 6: deterministic document assembly.

Per spec.md non-negotiable #1 ("assembly is deterministic file concatenation
+ Pandoc, never an LLM call"), everything here is pure, boring code -- no
network, no LLM, no I/O beyond reading the already-drafted per-leaf Markdown
files Phase 4/5 wrote to `data/runs/{run_id}/sections/{leaf_id}.md`. This
module is fully unit-testable without Pandoc installed (see
`tests/test_render_assemble.py`); `render/pandoc.py` is the only place that
shells out.

## Walk order and heading depth

`assemble_markdown` walks `RunState["outline"]` (a list of
`OutlineTreeNode.model_dump()` dicts, see `graph/state.py`) depth-first, in
the exact order the planner/outline-review screen produced -- this IS
"document order" for the whole pipeline, so no separate ordering key is
needed. A node's Markdown heading level is its recursion depth (1 for a
top-level node, 2 for its children, ...), which is exactly `len(parent_path)
+ 1` for the corresponding `SectionBrief` (Markdown ATX headings cap at 6
"#"s; deeper nodes are clamped there with a note in `assemble_run`'s
docstring since neither example spec nests that deep).

## Leaf splicing

A leaf (`children == []`) contributes its own heading plus the body Markdown
already written by the drafter (`graph.drafter.section_draft_path`), verbatim
except for the caption-renumbering pass below. A leaf with no draft file on
disk (flagged and never completed, or the run was rendered mid-flight) gets a
visible placeholder paragraph instead of vanishing silently or crashing the
whole assembly.

## The "references" leaf is never spliced (see DECISIONS.md)

Per Phase 3's own documented convention (`graph/planner.py`: a leaf whose
`FormatSpec` section has `word_range: null` -- e.g. "references" in both
example specs -- gets `target_words = 0` because "a bibliography is
auto-generated by Pandoc/CSL in Phase 6, not drafted prose"), any leaf whose
matching `SectionSpec.word_range` is `None` is skipped ENTIRELY here (no
heading, no body). Pandoc's `citeproc` filter (wired on in both
`templates/*.yaml` defaults, with `reference-section-title: "References"`)
appends the real bibliography at the end of the rendered document instead.

## Heading numbering

`heading_numbering.style` is never used to hand-write numeric prefixes onto
headings here. Both example specs' Pandoc defaults files already set
`number-sections: true`, so Pandoc/LaTeX (docx: Pandoc's own docx numbering)
does the numbering at render time from plain, unnumbered ATX headings -- one
numbering engine, not two disagreeing ones. `assemble_run` still surfaces
`number_sections = (spec.heading_numbering.style == "decimal")` on the
returned `AssembledDocument` so `render/pandoc.py` can pass an explicit
`--metadata=number-sections:...` override for a spec whose style is "none"
(no such spec exists yet, but the override costs nothing and keeps the two
representations from silently drifting apart later).

## Cross-references: figure/table numbering only, captions only

spec.md asks Phase 6 to "resolve cross-references if present (at minimum:
assemble figure/table numbering coherently across sections)". Per-leaf
drafting (Phase 4) is parallel and each leaf only sees a *snapshot* of
`DocumentState.figure_counter`/`table_counter` taken when it STARTED, so two
concurrently-drafted leaves can independently guess the same figure number.
This module fixes that up deterministically: `_renumber_caption_lines` walks
the final, in-order assembled text and rewrites each figure/table caption's
leading number to a running, globally-coherent sequence (chapter-scoped for
`chapter_decimal` numbering, matching each leaf's top-level outline
ancestor). This is a CODE-ONLY, no-LLM pass -- constraint #1.

Known, documented simplification: only the caption LINE's own number is
rewritten. In-prose references to a figure/table by number (e.g. "as shown in
Figure 2 above") are NOT tracked or rewritten -- Phase 4/5 defines no
cross-reference marker syntax for that (only `[@bibkey]` citation markers
exist), so there is nothing structured to resolve. A real fix would need the
drafter to emit a `\label`/`\ref`-style marker instead of a prose number,
which is out of scope for Phase 6.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from draftforge.formats.schema import CaptionRule, FormatSpec
from draftforge.graph.drafter import section_draft_path

MAX_HEADING_LEVEL = 6  # Markdown ATX heading levels only go up to 6 "#"s.

_MISSING_DRAFT_PLACEHOLDER = (
    "_[This section was not drafted (flagged or not yet completed) -- see "
    "the Review screen for its status.]_"
)


class AssembleError(ValueError):
    """Raised when a run cannot be assembled (e.g. no outline yet)."""


@dataclass
class AssembledSection:
    """One entry in the walked outline, for tests/debugging -- not written
    into the Markdown itself beyond the heading it already produced."""

    id: str
    title: str
    level: int
    is_leaf: bool
    spliced: bool  # False for skipped leaves (e.g. "references") and containers


@dataclass
class AssembledDocument:
    """Everything `render/pandoc.py` needs: the one concatenated Markdown
    string and a front-matter metadata dict ready to be dumped as a Pandoc
    `--metadata-file` YAML document."""

    markdown: str
    front_matter: dict[str, Any]
    number_sections: bool
    sections: list[AssembledSection] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Leaf body loading
# ---------------------------------------------------------------------------


def _read_leaf_body(run_id: str, leaf_id: str, *, sections_dir: Path | None = None) -> str:
    path = sections_dir / f"{leaf_id}.md" if sections_dir is not None else section_draft_path(run_id, leaf_id)
    if not path.exists():
        return _MISSING_DRAFT_PLACEHOLDER
    text = path.read_text(encoding="utf-8").strip()
    return text or _MISSING_DRAFT_PLACEHOLDER


# ---------------------------------------------------------------------------
# Caption renumbering (deterministic cross-reference resolution)
# ---------------------------------------------------------------------------


def _caption_leading_number_re(prefix: str) -> re.Pattern[str]:
    """Matches only the LEADING `<prefix> <number>` portion of a caption
    line -- deliberately not the whole line (see module docstring): only the
    number substring is replaced, everything else (bold markers, separator,
    descriptive text) is left exactly as the drafter wrote it."""
    esc = re.escape(prefix)
    return re.compile(rf"^(\*{{0,2}}{esc}\s+)(\d+(?:\.\d+)*)", re.IGNORECASE)


def _rewrite_caption_number(line: str, prefix: str, new_number: str) -> str | None:
    """Returns the rewritten line, or None if `line` isn't a caption for
    `prefix` at all (no rewrite needed)."""
    stripped = line.strip()
    pattern = _caption_leading_number_re(prefix)
    if not pattern.match(stripped):
        return None
    leading_ws = line[: len(line) - len(line.lstrip())]
    new_stripped = pattern.sub(lambda m: m.group(1) + new_number, stripped, count=1)
    return leading_ws + new_stripped


def _renumber_caption_lines(
    lines: list[str], rule: CaptionRule, kind: str, counters: dict[str, int]
) -> None:
    """Mutates `lines` in place, renumbering every caption matching `rule`'s
    prefix with a running counter. `rule.numbering == "none"` captions carry
    no number at all, so nothing to renumber -- left untouched."""
    if rule.numbering == "none":
        return
    for i, line in enumerate(lines):
        if rule.numbering == "chapter_decimal":
            candidate = f"{counters['chapter_index']}.{counters[f'{kind}_chapter'] + 1}"
        else:  # "decimal": one flat, document-wide sequence
            candidate = str(counters[kind] + 1)
        rewritten = _rewrite_caption_number(line, rule.prefix, candidate)
        if rewritten is None:
            continue
        lines[i] = rewritten
        if rule.numbering == "chapter_decimal":
            counters[f"{kind}_chapter"] += 1
        else:
            counters[kind] += 1


def _renumber_body(body: str, spec: FormatSpec, counters: dict[str, int]) -> str:
    lines = body.splitlines()
    _renumber_caption_lines(lines, spec.captions.figure, "figure", counters)
    _renumber_caption_lines(lines, spec.captions.table, "table", counters)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Outline walk -> Markdown
# ---------------------------------------------------------------------------


def assemble_markdown(
    run_id: str,
    outline: list[dict[str, Any]],
    spec: FormatSpec,
    *,
    sections_dir: Path | None = None,
) -> tuple[str, list[AssembledSection]]:
    """Walk `outline` depth-first (document order) and return
    `(assembled_markdown, sections)`. Pure aside from reading each leaf's
    on-disk `.md` file -- no LLM, no network (constraint #1)."""
    if not outline:
        raise AssembleError("outline is empty -- nothing to assemble")

    lines: list[str] = []
    walked: list[AssembledSection] = []
    counters = {"figure": 0, "table": 0, "figure_chapter": 0, "table_chapter": 0, "chapter_index": 0}

    def walk(nodes: list[dict[str, Any]], depth: int) -> None:
        for node in nodes:
            node_id = node["id"]
            title = node.get("title") or node_id
            children = node.get("children") or []
            is_leaf = not children
            level = min(depth, MAX_HEADING_LEVEL)

            if depth == 1:
                counters["chapter_index"] += 1
                counters["figure_chapter"] = 0
                counters["table_chapter"] = 0

            section_spec = spec.find_section(node_id)
            # See module docstring: a leaf whose spec section has no
            # word_range (e.g. "references") is auto-generated by Pandoc's
            # citeproc, never spliced from a drafted file.
            skip_entirely = is_leaf and section_spec is not None and section_spec.word_range is None
            if skip_entirely:
                walked.append(
                    AssembledSection(id=node_id, title=title, level=level, is_leaf=True, spliced=False)
                )
                continue

            lines.append(f"{'#' * level} {title}")
            lines.append("")

            if is_leaf:
                body = _read_leaf_body(run_id, node_id, sections_dir=sections_dir)
                body = _renumber_body(body, spec, counters)
                lines.append(body)
                lines.append("")
                walked.append(
                    AssembledSection(id=node_id, title=title, level=level, is_leaf=True, spliced=True)
                )
            else:
                walked.append(
                    AssembledSection(id=node_id, title=title, level=level, is_leaf=False, spliced=False)
                )
                walk(children, depth + 1)

    walk(outline, 1)
    markdown = "\n".join(lines).strip() + "\n"
    return markdown, walked


# ---------------------------------------------------------------------------
# Front matter
# ---------------------------------------------------------------------------

_ABSTRACT_PLACEHOLDER = (
    "[Abstract not yet drafted -- Phases 0-5 do not generate a separate "
    "abstract; supply one via run_config.front_matter.abstract before "
    "rendering.]"
)


def build_front_matter(spec: FormatSpec, run_config: dict[str, Any] | None) -> dict[str, Any]:
    """Build the Pandoc `--metadata-file` dict for this spec's title page.

    Values come from `run_config["front_matter"][field]` (preferred) or
    `run_config[field]` (fallback), else a visible bracketed placeholder --
    rendering must never fail just because the student hasn't supplied title-
    page metadata yet.

    Two known field-naming mismatches between `specs/*.json` and
    `templates/*.tex` (both pre-existing Phase 2 artifacts this phase does
    not own/edit) are bridged here rather than in the templates:
      - `ieee_report.json` calls its author field "authors" (plural); the
        template's `$for(author)$` loop expects the singular Pandoc
        convention "author". Both keys are emitted, aliased to the same
        value.
      - `university_thesis.json` calls its field "submission_date"
        (underscore, per the JSON schema's `^[a-z0-9_]+$` id pattern); the
        template writes `$submission-date$` (hyphen, Pandoc's own metadata
        convention). Every underscored field name is aliased to its
        hyphenated form too.
    """
    run_config = run_config or {}
    supplied: dict[str, Any] = dict(run_config.get("front_matter") or {})

    metadata: dict[str, Any] = {}
    for field_name in spec.front_matter.title_page_fields:
        value = supplied.get(field_name, run_config.get(field_name))
        if value is None:
            value = f"[{field_name.upper()}]"
        metadata[field_name] = value
        hyphenated = field_name.replace("_", "-")
        if hyphenated != field_name:
            metadata.setdefault(hyphenated, value)

    if "authors" in metadata:
        metadata.setdefault("author", metadata["authors"])

    if spec.front_matter.abstract_required:
        abstract = supplied.get("abstract", run_config.get("abstract"))
        metadata["abstract"] = abstract or _ABSTRACT_PLACEHOLDER

    date_value = supplied.get("date", run_config.get("date"))
    if date_value:
        metadata.setdefault("date", date_value)

    return metadata


# ---------------------------------------------------------------------------
# Public entrypoint
# ---------------------------------------------------------------------------


def assemble_run(
    run_id: str,
    run_state: dict[str, Any],
    spec: FormatSpec,
    *,
    sections_dir: Path | None = None,
) -> AssembledDocument:
    """Assemble one run's checkpointed `RunState` into a single Markdown
    document + front-matter dict. Pure/deterministic -- no LLM, no Pandoc
    (constraint #1); `render/pandoc.py` is the only later step that shells
    out. Raises `AssembleError` if the run has no outline yet."""
    outline = run_state.get("outline") or []
    if not outline:
        raise AssembleError(f"run {run_id!r} has no outline to assemble")

    markdown, sections = assemble_markdown(run_id, outline, spec, sections_dir=sections_dir)
    front_matter = build_front_matter(spec, run_state.get("run_config"))
    number_sections = spec.heading_numbering.style == "decimal"
    return AssembledDocument(
        markdown=markdown,
        front_matter=front_matter,
        number_sections=number_sections,
        sections=sections,
    )
